# Generated by Django 3.1.5 on 2021-01-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, default=None, max_length=255)),
                ('name_ru', models.CharField(blank=True, default=None, max_length=255)),
                ('name_uz', models.CharField(blank=True, default=None, max_length=255)),
            ],
        ),
    ]
